import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api/client";
import type { IncidentDetail } from "./incidentPresentation";
import { SignozLinks } from "./SignozLinks";
export function IncidentDetailPage() {
  const { incidentId = "" } = useParams(); const [incident, setIncident] = useState<IncidentDetail | null>(null); const [error, setError] = useState("");
  useEffect(() => { api<IncidentDetail>(`/operations/incidents/${incidentId}`).then(setIncident).catch((reason: Error) => setError(reason.message)); }, [incidentId]);
  if (error) return <main className="page"><div className="notice error">{error}</div></main>; if (!incident) return <main className="page"><div className="empty-state">Loading incident record...</div></main>;
  const records = [["Evidence", incident.evidence], ["Hypotheses", incident.hypotheses], ["Proposals", incident.proposals], ["Policy decisions", incident.policy_decisions], ["Approvals", incident.approvals], ["Executions", incident.executions], ["Verifications", incident.verifications], ["Rollbacks", incident.rollbacks], ["Notifications", incident.notifications]] as const;
  return <main className="page"><Link className="back-link" to="/ops/incidents">Back to incidents</Link><div className="page-heading"><div><span className="section-label">Incident detail</span><h1>{incident.category.replaceAll("_", " ")}</h1><p className="mono">{incident.incident_id}</p></div><span className="state-pill large">{incident.state}</span></div><section className="detail-layout"><div><section className="panel"><div className="panel-heading"><div><h2>Incident timeline</h2><p>Append-only lifecycle history.</p></div></div>{incident.timeline.length === 0 ? <div className="empty-state">No lifecycle events have been recorded yet.</div> : <ol className="timeline">{incident.timeline.map((event) => <li key={event.event_id}><span /> <div><b>{event.stage} / {event.outcome}</b><small>{event.summary} / {new Date(event.occurred_at).toLocaleString()}</small></div></li>)}</ol>}</section>{records.map(([title, values]) => <section className="panel detail-card" key={title}><h2>{title}</h2>{values.length === 0 ? <p className="muted">No {title.toLowerCase()} recorded.</p> : <pre className="record-json">{JSON.stringify(values, null, 2)}</pre>}</section>)}</div><aside><section className="panel detail-card"><h2>Incident summary</h2><dl><div><dt>Category</dt><dd>{incident.category.replaceAll("_", " ")}</dd></div><div><dt>Current state</dt><dd>{incident.state}</dd></div><div><dt>Created</dt><dd>{incident.created_at ? new Date(incident.created_at).toLocaleString() : "Not recorded"}</dd></div></dl></section><SignozLinks links={incident.signoz} /></aside></section></main>;
}
