import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
type Incident = { incident_id: string; category: string; state: string; created_at?: string };
export function IncidentListPage() {
  const [items, setItems] = useState<Incident[]>([]); const [activeOnly, setActiveOnly] = useState(false); const [category, setCategory] = useState(""); const [state, setState] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); const query = new URLSearchParams(); if (category) query.set("category", category); if (state) query.set("state", state); api<{items: Incident[]}>(`/operations/incidents?${query}`).then((value) => setItems(value.items)).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, [category, state]);
  const visible = activeOnly ? items.filter((item) => !["RESOLVED", "FAILED", "BLOCKED", "ESCALATED", "ROLLED_BACK"].includes(item.state)) : items;
  return <main className="page"><div className="page-heading"><div><span className="section-label">Reliability events</span><h1>Incidents</h1><p>Investigate active and historical application incidents.</p></div><span className="record-count">{visible.length} records</span></div><section className="panel"><div className="toolbar"><label className="filter-control"><input type="checkbox" checked={activeOnly} onChange={(event) => setActiveOnly(event.target.checked)} /> Show active only</label><label className="filter-control">Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All</option><option value="catalog_search">Catalog search</option><option value="inventory_dependency">Inventory</option><option value="order_backlog">Order backlog</option></select></label><label className="filter-control">State<select value={state} onChange={(event) => setState(event.target.value)}><option value="">All</option>{["RESOLVED", "BLOCKED", "APPROVAL_REQUIRED", "ESCALATED", "ROLLED_BACK"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label></div>{error ? <div className="notice error" role="alert">{error}</div> : loading ? <div className="empty-state">Loading incidents...</div> : visible.length === 0 ? <div className="empty-state"><b>No matching incidents</b><p>New alerts and historical events will appear in this table.</p></div> : <div className="table-wrap"><table><thead><tr><th>Incident</th><th>Category</th><th>Status</th><th>Created</th></tr></thead><tbody>{visible.map((item) => <tr key={item.incident_id}><td><Link className="incident-link" to={`/ops/incidents/${item.incident_id}`}>{item.incident_id.slice(0, 12)}</Link></td><td>{item.category.replaceAll("_", " ")}</td><td><span className="state-pill">{item.state}</span></td><td>{item.created_at ? new Date(item.created_at).toLocaleString() : "Not recorded"}</td></tr>)}</tbody></table></div>}</section></main>;
}
