import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api/client";

type Incident = { incident_id: string; category: string; state: string };
type Service = { available: boolean; detail: { queue_depth?: number; generated_orders?: number; status?: string } };
type Overview = { status: string; active_incidents: number; incident_count: number; services: { inventory: Service; worker: Service; workload: Service }; recent_incidents: Incident[] };
export function OverviewPage() {
  const [status, setStatus] = useState("Checking"); const [overview, setOverview] = useState<Overview | null>(null); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api<{status: string}>("/health"), api<Overview>("/operations/overview")]).then(([health, data]) => { setStatus(health.status); setOverview(data); }).catch((reason: Error) => setError(reason.message)); }, []);
  const services = overview?.services; const incidents = overview?.recent_incidents ?? [];
  return <main className="page"><div className="page-heading"><div><span className="section-label">Operations</span><h1>Environment overview</h1><p>Current application reliability posture and recent incident activity.</p></div><span className={`health-badge ${status === "ok" ? "success" : "warning"}`}><span /> {status === "ok" ? "Operational" : status}</span></div>{error && <div className="notice error" role="alert">{error}</div>}<section className="metric-grid"><article><span>API health</span><strong>{status === "ok" ? "Healthy" : "Unavailable"}</strong><small>Application control plane</small></article><article><span>Active incidents</span><strong>{overview?.active_incidents ?? "-"}</strong><small>{overview?.incident_count ?? 0} total recorded</small></article><article><span>Queue depth</span><strong>{services?.worker.detail.queue_depth ?? "-"}</strong><small>{services?.worker.available ? "Worker reporting" : "Worker unavailable"}</small></article><article><span>Workload orders</span><strong>{services?.workload.detail.generated_orders ?? "-"}</strong><small>{services?.workload.available ? "Persistent normal run" : "Workload unavailable"}</small></article></section><section className="panel"><div className="panel-heading"><div><h2>Recent incidents</h2><p>Latest reliability events recorded by Aegis.</p></div><Link to="/ops/incidents">View all incidents</Link></div>{incidents.length === 0 ? <div className="empty-state"><b>No incidents recorded</b><p>The environment is quiet. Incidents will appear here when an alert is accepted.</p></div> : <div className="table-wrap"><table><thead><tr><th>Category</th><th>State</th><th>Incident ID</th></tr></thead><tbody>{incidents.slice(0, 5).map((incident) => <tr key={incident.incident_id}><td><Link to={`/ops/incidents/${incident.incident_id}`}>{incident.category.replaceAll("_", " ")}</Link></td><td><span className="state-pill">{incident.state}</span></td><td className="mono">{incident.incident_id}</td></tr>)}</tbody></table></div>}</section></main>;
}
